### ISSUE TITLE
get_post_sections() throws notice in WP admin

### ISSUE THREAD

**Issue by cjg89** [UCF/UCF-Section-Plugin#31]
Notice: Undefined property: WP_Post_Type::$post_type in UCF-Section-Plugin/includes/ucf-section-common.php on line 238 

Probably need to return out of this function early when `is_admin()` is true.

**Comment by rjucf** [comment]
Can we close this issue? It looks like the offending code was removed in this commit:
https://github.com/UCF/UCF-Section-Plugin/commit/96ee5d7735fff0d1b71731b0fe62ba5e85de4501#diff-ef295f2531ed21db03dac117c343ee85

**Comment by jmbarne3** [comment]
The error has just moved to a different line:

`Notice: Undefined property: WP_Post_Type::$post_type in UCF-Section-Plugin/includes/ucf-section-common.php on line 248`

Click on the "All Degrees" list in the wp-admin to see the error.
